license="MIT"

[[mixins]]
config="elib.client.mixins.json"

[[mods]]
modId="elib"
version="${mod_version}"
displayName="Elib"
iconFile="assets/elib/icon.png"
authors="Elpu7"
description='''Client-side configuration library for Minecraft mods.'''

[[dependencies.elib]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.elib]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[features.elib]
javaVersion="[25,)"
